(() => {
  if(window.__MARKET_INTEL__)return; window.__MARKET_INTEL__=true;
  const root=document.createElement('div');root.id='market-intel-overlay';root.innerHTML=`<button id="mi-btn" aria-label="Open DRO AI Market Intelligence">DRO</button><section id="mi-panel" hidden><header><b>DRO / AI MARKET INTELLIGENCE</b><button id="mi-close">×</button></header><div id="mi-symbol">Detecting…</div><div id="mi-price">—</div><div id="mi-status">Connecting live stream…</div><div class="mi-grid"><div><small>Signal</small><strong id="mi-signal">—</strong></div><div><small>Forecast</small><strong id="mi-forecast">—</strong></div><div><small>Consensus</small><strong id="mi-consensus">—</strong></div><div><small>Confidence</small><strong id="mi-confidence">—</strong></div><div><small>Regime</small><strong id="mi-regime">—</strong></div><div><small>Pattern</small><strong id="mi-pattern">—</strong></div></div><div id="mi-event" hidden></div><div class="mi-actions"><button id="mi-scan">Deep Scan</button><button id="mi-coach">AI Coach</button></div><div class="mi-actions"><button id="mi-refresh">Refresh</button><button id="mi-details-btn">Details</button></div><div id="mi-details" hidden></div></section>`;
  const style=document.createElement('style');style.textContent='#market-intel-overlay{position:fixed;right:18px;bottom:18px;z-index:2147483647;font:12px system-ui,sans-serif;color:#eef5f1}#mi-btn,#mi-panel{background:#080c10;border:1px solid #2b3935;border-radius:14px;box-shadow:0 16px 45px #0009}#mi-btn{width:56px;height:48px;color:#7ff2a5;font-weight:900;cursor:pointer}#mi-panel{width:350px;padding:14px;display:grid;gap:10px;backdrop-filter:blur(14px)}#mi-panel header{display:flex;justify-content:space-between;color:#7ff2a5}#mi-close{background:none;border:0;color:#89958f;font-size:20px;cursor:pointer}.mi-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px}.mi-grid div{padding:9px;border:1px solid #24312d;border-radius:9px;background:#0c1210}.mi-grid small{display:block;color:#77847e;margin-bottom:3px}.mi-actions{display:flex;gap:7px}.mi-actions button{flex:1;border:1px solid #3a6a4a;border-radius:9px;padding:9px;background:#14251b;color:#9bf0b4;cursor:pointer}#mi-price{font-size:25px;font-weight:850}#mi-details{white-space:pre-wrap;line-height:1.5;color:#bdc8c2;max-height:300px;overflow:auto;border-top:1px solid #26332f;padding-top:9px}#mi-event{padding:9px;border:1px solid #6a4a2b;border-radius:9px;background:#17120d;color:#ffd39a;line-height:1.35}';document.documentElement.appendChild(style);document.body.appendChild(root);
  const $=id=>root.querySelector(id),btn=$('#mi-btn'),panel=$('#mi-panel');let currentSymbol=null,lastCycle=0,pageWatchTimer=null,livePrice=null,lastStreamEvent=0,streamRequestTimer=null,lastBridge='';
  function normalize(raw){const v=String(raw||'').toUpperCase().replace(/\s+/g,'').replace(/[-_/:]/g,'').replace(/^(BINANCE|KUCOIN|TRADINGVIEW)/,'');const m=v.match(/([A-Z0-9]{2,15})(USDT|USDC|BUSD|USD|PERP)/);return m?`${m[1]}USDT`.replace(/PERPUSDT$/,'USDT'):null;}
  function detect(){const u=`${location.hostname} ${location.pathname} ${location.search}`,t=document.title||'',body=document.body?.innerText||'';const c=[u.match(/(?:symbol=|pair=|market=)([A-Za-z0-9_-]+)/i)?.[1],u.match(/(?:spot|futures|perpetual|symbols?)\/([A-Za-z0-9_-]+)/i)?.[1],t.match(/[A-Za-z0-9]{2,15}[-_/]?(?:USDT|USDC|USD|PERP)/i)?.[0],body.match(/[A-Za-z0-9]{2,15}[-_/]?(?:USDT|USDC|USD|PERP)/i)?.[0]];return c.map(normalize).find(Boolean)||'BTCUSDT';}
  function detectInterval(){const all=`${location.pathname} ${location.search} ${document.title||''}`;return all.match(/(?:^|[?=&\s/_-])(1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|3d|1w)(?:$|[?&#\s/_-])/i)?.[1]||'15m';}
  function setSymbol(s){const n=normalize(s)||'BTCUSDT';if(n===currentSymbol)return;currentSymbol=n;$('#mi-symbol').textContent=n;window.marketIntelStream?.setSymbol(n);}
  function extractPrice(){for(const q of ['[data-testid*="price"]','[class*="price"]','[class*="Price"]','[data-test*="price"]','[aria-label*="price" i]'])for(const n of document.querySelectorAll(q)){const m=String(n.textContent||'').replace(/,/g,'').match(/\$?(\d+(?:\.\d+)?)/);const x=m?Number(m[1]):NaN;if(Number.isFinite(x)&&x>0)return x;}return null;}
  function context(){const pagePrice=extractPrice();return{source:'browser',symbol:detect(),interval:detectInterval(),pagePrice,observedAt:new Date().toISOString(),extraction:pagePrice!==null?'dom':'none'};}
  function publishBridge(data){try{const s=data?.signal||{},f=data?.forecast||{},c=data?.consensus||{},r=data?.risk||{},m=data?.multiTimeframe||{},p=data?.chartPatterns||{},md=data?.marketData||{};const compact={source:'DRO browser extension',symbol:currentSymbol,interval:detectInterval(),price:Number.isFinite(livePrice)?livePrice:null,pagePrice:extractPrice(),signal:s,forecast:f,consensus:c,risk:r,multiTimeframe:m,chartPatterns:p,marketData:{microstructure:md.microstructure||{},futures:{fundingRate:md.futures?.fundingRate,openInterest:md.futures?.openInterest},derivatives:md.derivatives||{}},news:(data?.news||[]).slice(0,8),events:(data?.events||[]).slice(0,8),warnings:(data?.warnings||[]).slice(0,12),observedAt:new Date().toISOString(),extraction:'extension-stream+page'};const encoded=JSON.stringify(compact);if(encoded===lastBridge)return;lastBridge=encoded;document.documentElement.setAttribute('data-dro-extension-context',encoded);window.dispatchEvent(new CustomEvent('dro-extension-context',{detail:compact}));}catch{}}
  function syncEnabled(){const value=document.documentElement.getAttribute('data-dro-extension');root.style.display=value==='off'?'none':'';}
  function render(data){lastCycle=Date.now();const s=data?.signal||{},f=data?.forecast||{},c=data?.consensus||{},m=data?.multiTimeframe||{},p=data?.chartPatterns||{},r=data?.risk||{};$('#mi-signal').textContent=s.signal||'NO TRADE';$('#mi-forecast').textContent=f.bias||'—';$('#mi-consensus').textContent=c.direction||'—';$('#mi-confidence').textContent=`${Math.round(s.confidence??c.confidence??0)}%`;$('#mi-regime').textContent=data?.technical?.structure?.trend||'UNKNOWN';$('#mi-pattern').textContent=p.pattern||'—';const events=data?.events||[],news=data?.news||[],a=data?.analysts||[],b=events.find(e=>e.impact==='BREAKING');$('#mi-event').hidden=!b;if(b)$('#mi-event').textContent=`⚠ BREAKING · ${b.source}\n${b.title}`;const views=(m.views||[]).map(v=>`${v.interval}: ${v.trend}/${v.momentum} (${v.confidence}%)`).join('\n')||'unavailable';const micro=data?.marketData?.microstructure||{},der=data?.marketData?.derivatives||{};$('#mi-details').textContent=[`Multi-timeframe: ${m.alignment||'INSUFFICIENT'} · score ${m.score??0}%`,`Conflict: ${m.conflict?'YES':'NO'}`,views,`Risk: ${r.level||'—'} · ${r.score??0}/100 · ${r.positionRisk||'—'}`,`Pattern: ${p.pattern||'—'} · Breakout: ${p.breakout||'—'} · ${p.confidence??0}%`,`Microstructure: OB ${micro.orderBookImbalance==null?'—':(micro.orderBookImbalance*100).toFixed(1)+'%'} · spread ${micro.spreadPct==null?'—':micro.spreadPct.toFixed(3)+'%'} · delta ${micro.deltaNotional==null?'—':micro.deltaNotional.toFixed(0)}`,`Derivatives basis: ${der.basisPct==null?'—':der.basisPct.toFixed(3)+'%'} · funding ${data?.marketData?.futures?.fundingRate??'—'} · OI ${data?.marketData?.futures?.openInterest??'—'}`,`Analysts: ${a.length}/33 · News: ${news.length} · Events: ${events.length}`,`Entry: ${s.entry??'n/a'} · Stop: ${s.stopLoss??'n/a'} · TP: ${(s.takeProfits||[]).join(', ')||'n/a'}`,`Warnings: ${(data?.warnings||[]).join(' | ')||'none'}`].join('\n');publishBridge(data);}
  function request(force=false){const ctx=context();setSymbol(ctx.symbol);$('#mi-status').textContent='DRO: 33 analysts + multi-timeframe + derivatives scan…';chrome.runtime.sendMessage({type:'MARKET_INTEL_LOOP',symbol:ctx.symbol,interval:ctx.interval,force,chartContext:{...ctx,pagePrice:livePrice??ctx.pagePrice,observedAt:new Date().toISOString(),extraction:ctx.extraction}},r=>{if(chrome.runtime.lastError||!r?.ok){$('#mi-status').textContent='Core unavailable — no fabricated result.';return;}if(Number.isFinite(livePrice))$('#mi-price').textContent=Number(livePrice).toLocaleString();render(r.data);const m=r.data?.multiTimeframe;$('#mi-status').textContent=`${m?.alignment||'UNKNOWN'} · ${ctx.interval} · ${r.cached?'cached':'fresh'} cycle`;});}
  function scheduleStreamRefresh(){if(panel.hidden||streamRequestTimer)return;streamRequestTimer=setTimeout(()=>{streamRequestTimer=null;request(false);},1500);}
  window.addEventListener('market-intel-stream',event=>{const d=event.detail||{};if(d.symbol&&currentSymbol&&d.symbol!==currentSymbol)return;if(d.type==='status'){$('#mi-status').textContent=d.status==='live'?'LIVE STREAM':'Stream '+String(d.status||'').toUpperCase();return;}lastStreamEvent=Date.now();if(d.type==='ticker'||d.type==='trade'){const price=Number(d.price);if(Number.isFinite(price)&&price>0){livePrice=price;$('#mi-price').textContent=price.toLocaleString();}}if(d.type==='depth'&&panel.hidden===false)scheduleStreamRefresh();});
  btn.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){if(Number.isFinite(livePrice))$('#mi-price').textContent=livePrice.toLocaleString();request();}};$('#mi-close').onclick=()=>panel.hidden=true;$('#mi-scan').onclick=()=>request(true);$('#mi-coach').onclick=()=>request(true);$('#mi-refresh').onclick=()=>request(true);$('#mi-details-btn').onclick=()=>$('#mi-details').hidden=!$('#mi-details').hidden;
  const observer=new MutationObserver(syncEnabled);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-dro-extension']});syncEnabled();
  watchPage();function watchPage(){clearInterval(pageWatchTimer);pageWatchTimer=setInterval(()=>{const s=detect();if(s!==currentSymbol){setSymbol(s);if(!panel.hidden)request(false);}},2000);}setSymbol(detect());setInterval(()=>{if(!panel.hidden&&Date.now()-lastCycle>25000)request(false);},5000);
})();
