(() => {
  if (window.__MARKET_INTEL__) return;
  window.__MARKET_INTEL__ = true;
  const root=document.createElement('div'); root.id='market-intel-overlay';
  root.innerHTML=`<button id="mi-btn" aria-label="Open Market Intelligence">MI</button><section id="mi-panel" hidden><header><b>MARKET/INTEL</b><button id="mi-close">×</button></header><div id="mi-symbol">Detecting…</div><div id="mi-price">—</div><div id="mi-status">Connecting live stream…</div><div class="mi-grid"><div><small>Signal</small><strong id="mi-signal">—</strong></div><div><small>Forecast</small><strong id="mi-forecast">—</strong></div><div><small>Consensus</small><strong id="mi-consensus">—</strong></div><div><small>Confidence</small><strong id="mi-confidence">—</strong></div><div><small>Regime</small><strong id="mi-regime">—</strong></div><div><small>Data</small><strong id="mi-data">—</strong></div></div><div id="mi-event" hidden></div><div class="mi-actions"><button id="mi-scan">Deep Scan</button><button id="mi-coach">AI Coach</button></div><div class="mi-actions"><button id="mi-refresh">Refresh</button><button id="mi-details-btn">Details</button></div><div id="mi-details" hidden></div></section>`;
  const style=document.createElement('style'); style.textContent='#market-intel-overlay{position:fixed;right:18px;bottom:18px;z-index:2147483647;font:12px system-ui,sans-serif;color:#eef5f1}#mi-btn,#mi-panel{background:#080c10;border:1px solid #2b3935;border-radius:14px;box-shadow:0 16px 45px #0009}#mi-btn{width:48px;height:48px;color:#7ff2a5;font-weight:900;cursor:pointer}#mi-panel{width:350px;padding:14px;display:grid;gap:10px;backdrop-filter:blur(14px)}#mi-panel header{display:flex;justify-content:space-between;color:#7ff2a5}#mi-close{background:none;border:0;color:#89958f;font-size:20px;cursor:pointer}.mi-symbol,.mi-status{color:#93a0af}#mi-price{font-size:25px;font-weight:850}.mi-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px}.mi-grid div{padding:9px;border:1px solid #24312d;border-radius:9px;background:#0c1210}.mi-grid small{display:block;color:#77847e;margin-bottom:3px}.mi-actions{display:flex;gap:7px}.mi-actions button{flex:1;border:1px solid #3a6a4a;border-radius:9px;padding:9px;background:#14251b;color:#9bf0b4;cursor:pointer}#mi-details{white-space:pre-wrap;line-height:1.5;color:#bdc8c2;max-height:260px;overflow:auto;border-top:1px solid #26332f;padding-top:9px}#mi-event{padding:9px;border:1px solid #6a4a2b;border-radius:9px;background:#17120d;color:#ffd39a;line-height:1.35}'; document.documentElement.appendChild(style);document.body.appendChild(root);
  const $=id=>root.querySelector(id), btn=$('#mi-btn'),panel=$('#mi-panel'); let currentSymbol=null,refreshTimer=null,pageWatchTimer=null,lastPagePrice=null,lastCycle=0;
  function normalize(raw){const v=String(raw||'').toUpperCase().replace(/\s+/g,'').replace(/[-_/:]/g,'').replace(/^(BINANCE|KUCOIN|TRADINGVIEW)/,'');const m=v.match(/([A-Z0-9]{2,15})(USDT|USDC|BUSD|USD|PERP)/);return m?`${m[1]}USDT`.replace(/PERPUSDT$/,'USDT'):null;}
  function detect(){const u=`${location.hostname} ${location.pathname} ${location.search}`,t=document.title||'',body=document.body?.innerText||'';const c=[u.match(/(?:symbol=|pair=|market=)([A-Za-z0-9_-]+)/i)?.[1],u.match(/(?:spot|futures|perpetual|symbols?)\/([A-Za-z0-9_-]+)/i)?.[1],t.match(/[A-Za-z0-9]{2,15}[-_/]?(?:USDT|USDC|USD|PERP)/i)?.[0],body.match(/[A-Za-z0-9]{2,15}[-_/]?(?:USDT|USDC|USD|PERP)/i)?.[0]];return c.map(normalize).find(Boolean)||'BTCUSDT';}
  function setSymbol(s,stream=true){const n=normalize(s)||'BTCUSDT';if(n===currentSymbol)return;currentSymbol=n;$('#mi-symbol').textContent=n;if(stream)window.marketIntelStream?.setSymbol(n);}
  function extractPrice(){for(const q of ['[data-testid*="price"]','[class*="price"]','[class*="Price"]','[data-test*="price"]','[aria-label*="price" i]'])for(const n of document.querySelectorAll(q)){const m=String(n.textContent||'').replace(/,/g,'').match(/\$?(\d+(?:\.\d+)?)/);const x=m?Number(m[1]):NaN;if(Number.isFinite(x)&&x>0)return x;}return null;}
  function render(data){lastCycle=Date.now();const s=data?.signal,f=data?.forecast,c=data?.consensus;$('#mi-signal').textContent=s?.signal||'NO TRADE';$('#mi-forecast').textContent=f?.bias||'—';$('#mi-consensus').textContent=c?.direction||'—';$('#mi-confidence').textContent=`${Math.round(s?.confidence??c?.confidence??0)}%`;$('#mi-regime').textContent=data?.technical?.structure?.trend||'UNKNOWN';$('#mi-data').textContent=s?.dataFresh===false||data?.dataValid===false?'STALE':data?.dataValid===true?'VALID':'CHECK';const events=Array.isArray(data?.events)?data.events:[],news=Array.isArray(data?.news)?data.news:[],a=Array.isArray(data?.analysts)?data.analysts:[];const b=events.find(e=>e.impact==='BREAKING');$('#mi-event').hidden=!b;if(b)$('#mi-event').textContent=`⚠ BREAKING · ${b.source}\n${b.title}`;$('#mi-details').textContent=[`Analysts: ${a.length}/33`,`Agreement: ${c?.agreement??0}%`,`News: ${news.length} · Events: ${events.length}`,`Entry: ${s?.entry??'n/a'}`,`Stop: ${s?.stopLoss??'n/a'}`,`TP: ${(s?.takeProfits||[]).join(', ')||'n/a'}`,`RR: ${s?.riskReward??'n/a'}`,`Data fresh: ${s?.dataFresh===true?'YES':'NO'}`,`Warnings: ${(data?.warnings||[]).join(' | ')||'none'}`].join('\n');}
  function request(force=false,mode='scan'){const sym=detect();setSymbol(sym);$('#mi-status').textContent=mode==='coach'?'AI Coach analyzing…':'33 analysts analyzing…';chrome.runtime.sendMessage({type:'MARKET_INTEL_LOOP',symbol:sym,interval:'15m',force},r=>{if(chrome.runtime.lastError||!r?.ok){$('#mi-status').textContent='Core unavailable — no fabricated result.';return;}render(r.data);const c=r.data?.consensus;$('#mi-status').textContent=`${c?.direction||'NEUTRAL'} · ${c?.confidence??0}% · ${r.cached?'cached':'fresh'} cycle`;$('#mi-details').hidden=false;});}
  function watch(){clearInterval(pageWatchTimer);pageWatchTimer=setInterval(()=>{const d=detect();if(d!==currentSymbol){setSymbol(d);if(!panel.hidden)request(false);}const p=extractPrice();if(Number.isFinite(p)&&p!==lastPagePrice&&!window.marketIntelStream){lastPagePrice=p;$('#mi-price').textContent=p.toLocaleString();}},2000);}
  btn.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){setSymbol(detect());request();}};$('#mi-close').onclick=()=>panel.hidden=true;$('#mi-scan').onclick=()=>request(true,'scan');$('#mi-coach').onclick=()=>request(true,'coach');$('#mi-refresh').onclick=()=>request(true);$('#mi-details-btn').onclick=()=>$('#mi-details').hidden=!$('#mi-details').hidden;
  window.addEventListener('market-intel-stream',e=>{const d=e.detail||{};if(d.status){$('#mi-status').textContent=d.status==='live'?'● Live market stream':`Stream: ${d.status}`;return;}if(d.type==='ticker'){setSymbol(d.symbol,false);$('#mi-price').textContent=Number.isFinite(d.price)?Number(d.price).toLocaleString():'—';$('#mi-status').textContent=`${d.change24hPct>=0?'+':''}${Number(d.change24hPct||0).toFixed(2)}% · live`;}});
  setSymbol(detect());refreshTimer=setInterval(()=>{if(!panel.hidden&&Date.now()-lastCycle>25000)request(false);},5000);watch();
})();
