(() => {
  if (window.__MARKET_INTEL__) return;
  window.__MARKET_INTEL__ = true;
  const root = document.createElement('div'); root.id = 'market-intel-overlay';
  root.innerHTML = `<button id="mi-btn" aria-label="DRO tools">DRO</button><section id="mi-panel" hidden><header><b>DRO</b><button id="mi-close">×</button></header><div class="mi-symbol" id="mi-symbol">BTCUSDT</div><div id="mi-price">—</div><div class="mi-tools"><button data-tool="signal">Signal</button><button data-tool="chart">Chart</button><button data-tool="mtf">MTF</button><button data-tool="orderbook">Book</button><button data-tool="derivatives">Deriv</button><button data-tool="news">News</button><button data-tool="risk">Risk</button><button data-tool="ai">AI</button></div><div class="mi-grid"><div><small>SIGNAL</small><strong id="mi-signal">—</strong></div><div><small>FORECAST</small><strong id="mi-forecast">—</strong></div><div><small>CONF</small><strong id="mi-confidence">—</strong></div><div><small>REGIME</small><strong id="mi-regime">—</strong></div></div><div id="mi-output">Double-tap DRO for tools.</div><div class="mi-actions"><button id="mi-scan">Deep Scan</button><button id="mi-refresh">Refresh</button></div></section>`;
  const style = document.createElement('style'); style.textContent = `#market-intel-overlay{position:fixed;left:auto;top:auto;right:12px;bottom:12px;z-index:2147483647;font:11px system-ui,sans-serif;color:#eef5f1;touch-action:none}#mi-btn{width:46px;height:38px;border:1px solid #2f5140;border-radius:12px;background:#080c10;color:#7ff2a5;font-weight:900;box-shadow:0 10px 30px #0008;cursor:grab;user-select:none;touch-action:none}#mi-btn:active{cursor:grabbing}#mi-panel{width:250px;margin-bottom:6px;padding:9px;background:#080c10;border:1px solid #2b3935;border-radius:12px;box-shadow:0 16px 40px #0009;backdrop-filter:blur(14px);gap:7px}#mi-panel header{display:flex;justify-content:space-between;color:#7ff2a5}#mi-close{background:none;border:0;color:#89958f;font-size:17px}.mi-symbol{font-weight:800}#mi-price{font-size:18px;font-weight:850}.mi-tools{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.mi-tools button,.mi-actions button{min-width:0;padding:5px 3px;border:1px solid #294936;border-radius:7px;background:#101a14;color:#a8efbc;font-size:9px;cursor:pointer}.mi-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px}.mi-grid div{padding:5px;border:1px solid #202d27;border-radius:7px;background:#0c1210}.mi-grid small{display:block;color:#728079;font-size:7px}.mi-grid strong{font-size:10px}.mi-actions{display:flex;gap:4px}.mi-actions button{flex:1}.mi-output{min-height:30px;padding:6px;border-top:1px solid #202d27;color:#b9c5be;white-space:pre-wrap;line-height:1.35}#mi-event{color:#ffd39a}`; document.documentElement.appendChild(style); document.body.appendChild(root);
  const $ = id => root.querySelector(id), btn = $('#mi-btn'), panel = $('#mi-panel');
  let currentSymbol = null, livePrice = null, lastCycle = 0, streamTimer = null, lastData = null, dragging = false, moved = false, sx = 0, sy = 0, sl = 0, st = 0;
  const tools = ['signal','chart','mtf','orderbook','derivatives','news','risk','ai'];
  function normalize(raw){const v=String(raw||'').toUpperCase().replace(/\s+/g,'').replace(/[-_/:]/g,'').replace(/^(BINANCE|KUCOIN|TRADINGVIEW)/,'');const m=v.match(/([A-Z0-9]{2,15})(USDT|USDC|BUSD|USD|PERP)/);return m?`${m[1]}USDT`:'BTCUSDT';}
  function detect(){const s=`${location.hostname} ${location.pathname} ${location.search} ${document.title||''}`;return normalize(s.match(/[A-Za-z0-9]{2,15}[-_/]?(?:USDT|USDC|USD|PERP)/i)?.[0]);}
  function interval(){const s=`${location.pathname} ${location.search} ${document.title||''}`;return s.match(/(?:^|[?=&\s/_-])(1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|3d|1w)(?:$|[?&#\s/_-])/i)?.[1]||'15m';}
  function pagePrice(){for(const q of ['[data-testid*="price"]','[class*="price"]','[class*="Price"]','[data-test*="price"]','[aria-label*="price" i]'])for(const n of document.querySelectorAll(q)){const m=String(n.textContent||'').replace(/,/g,'').match(/\$?(\d+(?:\.\d+)?)/);const x=m?Number(m[1]):NaN;if(Number.isFinite(x)&&x>0)return x}return null}
  async function savePos(){await chrome.storage.local.set({droPosition:{left:root.style.left,top:root.style.top,right:root.style.right,bottom:root.style.bottom}})}
  async function loadPos(){const x=await chrome.storage.local.get('droPosition');const p=x?.droPosition;if(!p)return;for(const k of ['left','top','right','bottom'])root.style[k]=p[k]||'';}
  function clamp(){const r=root.getBoundingClientRect();let x=Math.max(2,Math.min(innerWidth-r.width-2,r.left)),y=Math.max(2,Math.min(innerHeight-r.height-2,r.top));root.style.left=x+'px';root.style.top=y+'px';root.style.right='auto';root.style.bottom='auto'}
  function startDrag(e){dragging=true;moved=false;const r=root.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;btn.setPointerCapture?.(e.pointerId)}
  function moveDrag(e){if(!dragging)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;root.style.left=Math.max(2,Math.min(innerWidth-rwidth(),sl+dx))+'px';root.style.top=Math.max(2,Math.min(innerHeight-rheight(),st+dy))+'px';root.style.right='auto';root.style.bottom='auto'}
  function rwidth(){return root.getBoundingClientRect().width||46} function rheight(){return root.getBoundingClientRect().height||38}
  btn.addEventListener('pointerdown',startDrag);btn.addEventListener('pointermove',moveDrag);btn.addEventListener('pointerup',async e=>{if(!dragging)return;dragging=false;if(!moved){panel.hidden=!panel.hidden;if(!panel.hidden)request(false)}else await savePos()});
  btn.addEventListener('dblclick',e=>{e.preventDefault();panel.hidden=false;request(false)});
  $('#mi-close').onclick=()=>panel.hidden=true;
  function toolView(tool){const d=lastData||{},s=d.signal||{},f=d.forecast||{},r=d.risk||{},m=d.multiTimeframe||{},p=d.chartPatterns||{},md=d.marketData||{},micro=md.microstructure||{},der=md.derivatives||{},fu=md.futures||{};const views=(m.views||[]).map(v=>`${v.interval}: ${v.trend}/${v.momentum} ${v.confidence??0}%`).join('\n');const map={signal:`${s.signal||'NO TRADE'} · ${Math.round(s.confidence??0)}%\nEntry ${s.entry??'—'} · SL ${s.stopLoss??'—'}\nTP ${(s.takeProfits||[]).slice(0,2).join(', ')||'—'}`,chart:`LIVE OHLCV\n${currentSymbol} · ${interval()}\nOpen ${md.spot?.price??'—'} · page ${pagePrice()??'—'}\nUse full chart in AI chat.`,mtf:`${m.alignment||'INSUFFICIENT'} · ${m.score??0}%\n${views||'No MTF data'}`,orderbook:`Imbalance ${micro.orderBookImbalance==null?'—':(micro.orderBookImbalance*100).toFixed(1)+'%'}\nSpread ${micro.spreadPct==null?'—':micro.spreadPct.toFixed(3)+'%'}\nDelta ${micro.deltaNotional??'—'}`,derivatives:`Basis ${der.basisPct??'—'}%\nFunding ${fu.fundingRate??'—'}\nOI ${fu.openInterest??'—'}`,news:`${(d.news||[]).slice(0,3).map(n=>n.title||n.source).join('\n')||'No fresh news'}`,risk:`${r.level||'—'} · ${r.score??0}/100\n${r.positionRisk||'—'}\n${(d.warnings||[]).slice(0,2).join('\n')}`,ai:'AI Coach is available from the AI chat. Ask: Why this signal?'};$('#mi-output').textContent=map[tool]||'Ready';}
  document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>toolView(b.dataset.tool)));
  function render(data){lastData=data;lastCycle=Date.now();const s=data?.signal||{},f=data?.forecast||{},c=data?.consensus||{};$('#mi-symbol').textContent=currentSymbol;$('#mi-signal').textContent=s.signal||'NO TRADE';$('#mi-forecast').textContent=f.bias||'—';$('#mi-confidence').textContent=`${Math.round(s.confidence??c.confidence??0)}%`;$('#mi-regime').textContent=data?.technical?.structure?.trend||'UNKNOWN';}
  function request(force=false){const symbol=detect();if(symbol!==currentSymbol){currentSymbol=symbol;window.marketIntelStream?.setSymbol(symbol)}const ctx={source:'browser',symbol:currentSymbol,interval:interval(),pagePrice:livePrice??pagePrice(),observedAt:new Date().toISOString(),extraction:'extension'};chrome.runtime.sendMessage({type:'MARKET_INTEL_LOOP',symbol:currentSymbol,interval:ctx.interval,force,chartContext:ctx},r=>{if(chrome.runtime.lastError||!r?.ok){$('#mi-output').textContent='Core unavailable — no fabricated result.';return}render(r.data);$('#mi-price').textContent=Number.isFinite(livePrice)?livePrice.toLocaleString():(r.data?.marketData?.spot?.price??'—');});}
  window.addEventListener('market-intel-stream',e=>{const d=e.detail||{};if(d.symbol&&currentSymbol&&d.symbol!==currentSymbol)return;if(d.type==='ticker'||d.type==='trade'){const p=Number(d.price);if(Number.isFinite(p)&&p>0){livePrice=p;$('#mi-price').textContent=p.toLocaleString();}}if(d.type==='depth'&&!panel.hidden&&!streamTimer){streamTimer=setTimeout(()=>{streamTimer=null;request(false)},1500)}});
  const obs=new MutationObserver(()=>{const off=document.documentElement.getAttribute('data-dro-extension')==='off';root.style.display=off?'none':''});obs.observe(document.documentElement,{attributes:true,attributeFilter:['data-dro-extension']});
  setInterval(()=>{const s=detect();if(s!==currentSymbol){currentSymbol=s;window.marketIntelStream?.setSymbol(s);if(!panel.hidden)request(false)}},1500);
  loadPos().then(()=>clamp()); window.addEventListener('resize',clamp); currentSymbol=detect(); window.marketIntelStream?.setSymbol(currentSymbol);
})();