const $=id=>document.getElementById(id);const state={tab:null,symbol:'BTCUSDT',interval:'15m',last:null,busy:false};
function ensureHealthMarkup(){if($('forecastHealth'))return;const anchor=document.querySelectorAll('.risk')[1];const html='<section class="health"><div><small>FORECAST HEALTH</small><b id="forecastHealth">—</b></div><div><small>HIT RATE</small><b id="hitRate">—</b></div><div><small>DATA AGE</small><b id="dataAge">—</b></div><div><small>MTF</small><b id="mtf">—</b></div></section>';if(anchor)anchor.insertAdjacentHTML('afterend',html);else document.querySelector('main')?.insertAdjacentHTML('beforeend',html);}
function detectSymbol(tab){const text=`${tab?.url||''} ${tab?.title||''}`.toUpperCase();const a=text.match(/\b([A-Z]{2,12})USDT\b/),b=text.match(/\b([A-Z]{2,12})(?:USD|USDC)\b/);return a?.[1]?`${a[1]}USDT`:b?.[1]?`${b[1]}USDT`:'BTCUSDT';}
function detectInterval(tab){const text=`${tab?.url||''} ${tab?.title||''}`.toLowerCase();const m=text.match(/(?:interval|timeframe|resolution)[=/_-]?(1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|3d|1w)/);return m?.[1]||'15m';}
function setStatus(text,online=true){$('status').textContent=text;$('status').classList.toggle('offline',!online);}
function number(value,digits=2){const n=Number(value);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:digits}):'—';}
function setOptional(id,value){const el=$(id);if(el)el.textContent=value;}
function show(data,symbol){ensureHealthMarkup();state.last=data;const signal=data?.signal||{},forecast=data?.forecast||{},consensus=data?.consensus||{},technical=data?.technical||{},risk=data?.risk||{},pattern=data?.chartPatterns||{},mtf=data?.multiTimeframe||{},fm=data?.forecastMetrics||{};$('symbol').textContent=symbol;$('price').textContent=Number(data?.marketData?.spot?.price)>0?number(data.marketData.spot.price,8):'—';$('signal').textContent=signal.signal||'NO TRADE';$('forecast').textContent=forecast.bias||'UNAVAILABLE';$('consensus').textContent=consensus.direction||consensus.signal||'—';const confidence=Number(signal.confidence??forecast.confidence??technical.confidence);$('confidence').textContent=Number.isFinite(confidence)?`${Math.round(confidence)}%`:'—';const total=Number(fm.total),wins=Number(fm.wins),rate=Number(fm.winRate);setOptional('forecastHealth',Number.isFinite(total)&&total>0?`${total} evals`:'NO HISTORY');setOptional('hitRate',Number.isFinite(rate)?`${Math.round(rate*100)}%`:'—');const observedAt=Date.parse(data?.chartContext?.observedAt||'');const ageMs=Number.isFinite(observedAt)?Math.max(0,Date.now()-observedAt):null;setOptional('dataAge',ageMs===null?'—':ageMs<1000?'LIVE':ageMs<60000?`${Math.round(ageMs/1000)}s`:ageMs<3600000?`${Math.round(ageMs/60000)}m`:`${Math.round(ageMs/3600000)}h`);setOptional('mtf',mtf.alignment||'—');$('meta').textContent=`${technical.structure?.trend||'Market'} · ${data?.interval||state.interval} · ${data?.analysts?.length||0} analysts · ${data?.news?.length||0} news · ${Number.isFinite(wins)?wins:'0'} wins`;$('warning').textContent=(data?.warnings||[]).slice(0,4).join('\n');$('entry').textContent=number(signal.entry,8);$('sl').textContent=number(signal.stopLoss,8);$('tp').textContent=number(signal.takeProfits?.[0],8);$('rr').textContent=number(signal.riskReward,2);$('riskLevel').textContent=risk.level||'—';$('positionRisk').textContent=risk.positionRisk||'—';$('pattern').textContent=pattern.pattern||'—';$('breakout').textContent=pattern.breakout||'—';$('detailsPanel').textContent=JSON.stringify({forecastHealth:fm,multiTimeframe:mtf,risk,chartPatterns:pattern,signal,forecast,consensus,technical,chartContext:data?.chartContext||null,newsImpact:data?.newsImpact||null,events:data?.events||[],news:data?.news||[]},null,2).slice(0,14000);setStatus('●',true);}
async function loadMetrics(symbol){try{const base=await chrome.runtime.sendMessage({type:'GET_FORECAST_METRICS',symbol});return base?.ok?base.metrics:null;}catch{return null;}}
async function getActiveTab(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});return tabs[0];}
async function run(force=false){if(state.busy)return;state.busy=true;$('refresh').disabled=true;$('scan').disabled=true;$('meta').textContent=force?'Running deep market scan…':'Loading live intelligence…';try{state.tab=await getActiveTab();state.symbol=detectSymbol(state.tab);state.interval=detectInterval(state.tab);$('symbol').textContent=state.symbol;const response=await chrome.runtime.sendMessage({type:'MARKET_INTEL_LOOP',symbol:state.symbol,interval:state.interval,force});if(!response?.ok)throw new Error(response?.error||'Core unavailable');const metrics=await loadMetrics(state.symbol);response.data.forecastMetrics=metrics;show(response.data,state.symbol);}catch(error){setStatus('○',false);$('warning').textContent=String(error?.message||error);$('meta').textContent='Core unavailable — no fabricated market result shown.';}finally{state.busy=false;$('refresh').disabled=false;$('scan').disabled=false;}}
$('refresh').addEventListener('click',()=>run(true));$('scan').addEventListener('click',()=>run(true));$('details').addEventListener('click',()=>{$('detailsPanel').hidden=!$('detailsPanel').hidden;});run(false);
