'use client';
import React,{useEffect,useMemo,useState} from 'react';
import MarketChart from '@/app/components/MarketChart';
type Props={symbol:string;interval:string;context:unknown;fa?:boolean};
type ExtensionSnapshot={symbol?:string;interval?:string;pagePrice?:number|null;price?:number|null;signal?:unknown;forecast?:unknown;consensus?:unknown;risk?:unknown;multiTimeframe?:unknown;chartPatterns?:unknown;marketData?:unknown;news?:unknown[];events?:unknown[];warnings?:string[];observedAt?:string;extraction?:string};
const toggleStyle=(active:boolean):React.CSSProperties=>({border:'1px solid #315443',borderRadius:9,padding:'7px 9px',background:active?'#15351f':'#0b1110',color:active?'#8ff5ae':'#7f8b86',cursor:'pointer',fontWeight:800,minWidth:52});
export default function AIChat({symbol,interval,context,fa=false}:Props){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[extensionEnabled,setExtensionEnabled]=useState(true),[extension,setExtension]=useState<ExtensionSnapshot|null>(null),[chartEnabled,setChartEnabled]=useState(true);
 const readExtension=()=>{try{const raw=document.documentElement.getAttribute('data-dro-extension-context');setExtension(raw?JSON.parse(raw):null)}catch{setExtension(null)}};
 useEffect(()=>{try{const a=localStorage.getItem('dro-ai-extension-enabled');if(a!==null)setExtensionEnabled(a==='1');const c=localStorage.getItem('dro-ai-chart-enabled');if(c!==null)setChartEnabled(c==='1')}catch{}readExtension();const f=()=>readExtension();addEventListener('dro-extension-context',f);return()=>removeEventListener('dro-extension-context',f)},[]);
 useEffect(()=>{document.documentElement.setAttribute('data-dro-ai-extension',extensionEnabled?'on':'off');try{localStorage.setItem('dro-ai-extension-enabled',extensionEnabled?'1':'0')}catch{}},[extensionEnabled]);
 useEffect(()=>{try{localStorage.setItem('dro-ai-chart-enabled',chartEnabled?'1':'0')}catch{}},[chartEnabled]);
 useEffect(()=>{if(!open)return;fetch('/api/chat',{cache:'no-store'}).then(r=>r.json()).then(d=>setStatus(d.configured?(extensionEnabled?'AI online · DRO tool':'AI online · DRO off'):'AI server key missing')).catch(()=>setStatus('AI connection unavailable'))},[open,extensionEnabled]);
 const mergedContext=useMemo(()=>({symbol,interval,liveContext:context,extension:extensionEnabled?extension:null,chart:{enabled:chartEnabled,source:'live OHLCV'}}),[symbol,interval,context,extensionEnabled,extension,chartEnabled]);
 const send=async()=>{const message=input.trim();if(!message||busy)return;setBusy(true);setError('');setAnswer('');try{let r:Response|null=null,d:any=null;for(let a=0;a<2;a++){r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,symbol,interval,context:JSON.stringify(mergedContext),extensionContext:extensionEnabled?JSON.stringify(extension||{}):'',extensionEnabled,toolContext:{dro:extensionEnabled,chart:chartEnabled,symbol,interval}}),cache:'no-store'});d=await r.json();if(r.ok)break;if(r.status===429&&a===0){const s=Math.max(1,Math.min(6,Number(r.headers.get('retry-after'))||2));setStatus(fa?`محدودیت موقت؛ ${s} ثانیه…`:`Rate limited; retrying in ${s}s…`);await new Promise(x=>setTimeout(x,s*1000));continue}break}if(!r?.ok)throw new Error(d?.error||'AI unavailable');setAnswer(d.text||'No response');setInput('');setStatus(extensionEnabled?'DRO active · live response':'Response received')}catch(e){setError(e instanceof Error?e.message:'AI unavailable');setStatus('AI communication error')}finally{setBusy(false)}};
 return React.createElement(React.Fragment,null,React.createElement('button',{className:'aiFab',onClick:()=>setOpen(!open),title:'DRO AI'},open?'×':'AI'),open&&React.createElement('aside',{className:'aiChat',dir:fa?'rtl':'ltr'},React.createElement('div',{className:'aiHead'},React.createElement('div',null,React.createElement('b',null,'DRO AI'),React.createElement('small',null,`${symbol} · ${interval} · ${extensionEnabled?'DRO ON':'DRO OFF'}`)),React.createElement('button',{onClick:()=>setOpen(false)},'×')),React.createElement('div',{className:'aiBody'},React.createElement('small',{className:'muted'},status),chartEnabled&&React.createElement(MarketChart,{symbol,interval,fa}),answer&&React.createElement('div',{className:'aiAnswer'},answer),extensionEnabled&&extension&&React.createElement('div',{className:'droExtContext'},React.createElement('b',null,'DRO TOOL · LIVE'),React.createElement('span',null,`${extension.symbol||symbol} · ${extension.extraction||'stream'}`)),error&&React.createElement('p',{className:'down'},error)),React.createElement('div',{className:'aiInput'},React.createElement('textarea',{value:input,onChange:e=>setInput((e.currentTarget as HTMLTextAreaElement).value),onKeyDown:e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}},placeholder:fa?'پیام خود را بنویسید…':'Ask DRO…'}),React.createElement('div',{className:'aiInputActions'},React.createElement('button',{style:toggleStyle(extensionEnabled),onClick:()=>{setExtensionEnabled(v=>!v);setError('')},title:'Toggle DRO tool'},'🌳 ',extensionEnabled?'DRO':'OFF'),React.createElement('button',{style:toggleStyle(chartEnabled),onClick:()=>setChartEnabled(v=>!v),title:'Toggle live chart'},'⌁ ',chartEnabled?'CHART':'OFF'),React.createElement('button',{className:'sendBtn',onClick:()=>void send(),disabled:busy||!input.trim()},busy?'…':fa?'ارسال':'Send')))))
}
