'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

type Market={symbol:string;name:string;price:number;change24h:number;source?:string;quality?:string};
type Loop={symbol:string;interval:string;generatedAt:string;dataValid:boolean;market?:{warnings?:string[]};marketData?:{futures?:{price:number|null;fundingRate:number|null;openInterest:number|null};spot?:{price:number|null;volume24h:number|null}};signal?:{direction?:string;confidence?:number;entry?:number|null;stopLoss?:number|null;takeProfit?:number|null;rr?:number|null;invalidation?:string};forecast?:{bias?:string;confidence?:number;expectedLow?:number|null;expectedHigh?:number|null;horizonMs?:number};consensus?:{direction?:string;confidence?:number;score?:number;views?:number};risk?:{level?:string;score?:number;positionRisk?:string;reasons?:string[]};multiTimeframe?:{alignment?:string;score?:number;conflict?:boolean;views?:unknown[]};chartPatterns?:{primary?:string;breakout?:string;confidence?:number;warnings?:string[]};newsImpact?:{level?:string;breakingCount?:number;highImpactCount?:number;latestAgeMs?:number|null};eventReaction?:{level?:string;urgency?:string;direction?:string;score?:number;reasons?:string[]};warnings?:string[];news?:Array<{title:string;source:string;publishedAt:string;url:string;category?:string}>};
type Metrics={total:number;wins:number;losses:number;winRate:number|null;averageReturnPct:number|null;averageCalibrationGap:number|null};
type Lang='auto'|'en'|'fa';
const tr={en:{markets:'Markets',intel:'Intelligence',news:'News',watch:'Watchlist',hero:'LIVE MARKET',sub:'intelligence that earns trust through validation',refresh:'Refresh',deep:'DEEP SCAN',signal:'SIGNAL',forecast:'FORECAST',consensus:'CONSENSUS',risk:'RISK',mtf:'MULTI-TIMEFRAME',newsPulse:'NEWS PULSE',learning:'FORECAST TRACK RECORD',thesis:'THESIS & WARNINGS',no:'NO TRADE',fresh:'LIVE',stale:'LIMITED',history:'No evaluated history yet',install:'Install App'},fa:{markets:'بازارها',intel:'هوش بازار',news:'اخبار',watch:'دیده‌بان',hero:'هوش زنده بازار',sub:'تحلیلی که با اعتبارسنجی بهتر می‌شود، نه با حدس',refresh:'به‌روزرسانی',deep:'اسکن عمیق',signal:'سیگنال',forecast:'پیش‌بینی',consensus:'اجماع تحلیلگران',risk:'ریسک',mtf:'چندبازه‌ای',newsPulse:'نبض اخبار',learning:'سابقه اعتبارسنجی پیش‌بینی',thesis:'منطق و هشدارها',no:'بدون معامله',fresh:'زنده',stale:'محدود',history:'هنوز سابقه ارزیابی کافی نیست',install:'نصب اپ'}};
function money(v:number|null|undefined){return v==null||!Number.isFinite(v)?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:v>100?0:2}).format(v)}
function pct(v:number|null|undefined){return v==null||!Number.isFinite(v)?'—':`${v.toFixed(1)}%`}
function age(s?:string){if(!s)return'—';const m=Math.max(0,Math.floor((Date.now()-Date.parse(s))/60000));return m<1?'now':m<60?`${m}m`:`${Math.floor(m/60)}h`}
function dirClass(v?:string){return v==='LONG'||v==='BULLISH'?'up':v==='SHORT'||v==='BEARISH'?'down':''}

export default function Home(){
 const [markets,setMarkets]=useState<Market[]>([]),[loop,setLoop]=useState<Loop|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[symbol,setSymbol]=useState('BTCUSDT'),[interval,setIntervalValue]=useState('15m'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[language,setLanguage]=useState<Lang>('auto'),[installEvent,setInstallEvent]=useState<any>(null);
 const active=language==='auto'?(typeof navigator!=='undefined'&&navigator.language.toLowerCase().startsWith('fa')?'fa':'en'):language,t=tr[active];
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const [m,l,f]=await Promise.all([fetch('/api/market',{cache:'no-store'}),fetch(`/api/loop?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}`,{cache:'no-store'}),fetch(`/api/forecast-metrics?symbol=${encodeURIComponent(symbol)}`,{cache:'no-store'})]);const md=await m.json(),ld=await l.json(),fd=await f.json();if(!m.ok||!l.ok)throw new Error(ld.error||md.error||'Live intelligence unavailable');setMarkets(md.markets??[]);setLoop(ld);setMetrics(fd.metrics??null)}catch(e){setError(e instanceof Error?e.message:'Unable to load live intelligence')}finally{setLoading(false)}},[symbol,interval]);
 useEffect(()=>{refresh();const id=setInterval(refresh,30000);return()=>clearInterval(id)},[refresh]);
 useEffect(()=>{const f=(e:Event)=>{e.preventDefault();setInstallEvent(e)};window.addEventListener('beforeinstallprompt',f);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>window.removeEventListener('beforeinstallprompt',f)},[]);
 const install=async()=>{if(!installEvent)return;installEvent.prompt();await installEvent.userChoice;setInstallEvent(null)};
 const stories=useMemo(()=>loop?.news??[],[loop]);
 const confidence=loop?.signal?.confidence??0;
 const health=loop?.dataValid?'LIVE':'LIMITED';
 const mtf=loop?.multiTimeframe?.alignment??'INSUFFICIENT';
 return <main className="shell" dir={active==='fa'?'rtl':'ltr'}>
  <header className="top"><a className="brand" href="#top">MARKET<span>/</span>INTEL</a><nav className="nav"><a href="#markets">{t.markets}</a><a href="#intelligence">{t.intel}</a><a href="#news">{t.news}</a><a href="#watchlist">{t.watch}</a></nav><div className="controls"><select value={language} onChange={e=>setLanguage(e.target.value as Lang)}><option value="auto">Auto</option><option value="en">English</option><option value="fa">فارسی</option></select><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','ADAUSDT'].map(x=><option key={x}>{x}</option>)}</select><select value={interval} onChange={e=>setIntervalValue(e.target.value)}>{['5m','15m','1h','4h','1d'].map(x=><option key={x}>{x}</option>)}</select>{installEvent&&<button className="install" onClick={install}>{t.install}</button>}<button className="refresh" onClick={refresh}>{loading?'…':t.refresh}</button></div></header>
  <section className="hero" id="top"><div><div className="eyebrow"><i className="dot"/>{health} · {symbol} · {interval}</div><h1>{t.hero}<br/><em>{t.sub}</em></h1><p>Live market data → technical structure → multi-timeframe analysis → 33 analyst views → consensus → risk controls → forecast evaluation. No fabricated market values.</p></div><div className="status"><b>{health}</b><span>Cycle {loop?.cycleId??'—'}</span><small>{loop?.generatedAt?`${age(loop.generatedAt)} ago`:'—'}</small>{error&&<small className="down">{error}</small>}</div></section>
  <section className="ticker" id="markets">{markets.slice(0,6).map(x=><button className={`card ${x.symbol===symbol?'selected':''}`} key={x.symbol} onClick={()=>setSymbol(x.symbol)}><div className="label">{x.symbol.replace('USDT','')}/USD</div><div className="price">{money(x.price)}</div><div className={x.change24h>=0?'up':'down'}>{x.change24h>=0?'+':''}{x.change24h.toFixed(2)}%</div><div className="mini">{x.quality||'live'} · {x.source||'provider'}</div></button>)}</section>
  <section className="command" id="intelligence"><div className="commandTop"><div><div className="label">{t.signal}</div><div className="big"><strong className={dirClass(loop?.signal?.direction)}>{loop?.signal?.direction||t.no}</strong><b>{pct(confidence)}</b></div><div className="meter"><i style={{width:`${Math.min(100,Math.max(0,confidence))}%`}}/></div><button className="deep" onClick={refresh}>{t.deep}</button></div><div className="statGrid"><article><small>{t.forecast}</small><strong className={dirClass(loop?.forecast?.bias)}>{loop?.forecast?.bias||'UNAVAILABLE'}</strong><span>{pct(loop?.forecast?.confidence)} · {money(loop?.forecast?.expectedLow)} — {money(loop?.forecast?.expectedHigh)}</span></article><article><small>{t.consensus}</small><strong>{loop?.consensus?.direction||'NO DATA'}</strong><span>{pct(loop?.consensus?.confidence)} · {loop?.consensus?.views??0} views</span></article><article><small>{t.risk}</small><strong>{loop?.risk?.level||'UNKNOWN'}</strong><span>{loop?.risk?.positionRisk||'—'} · score {loop?.risk?.score??'—'}</span></article><article><small>{t.mtf}</small><strong>{mtf.replaceAll('_',' ')}</strong><span>{loop?.multiTimeframe?.conflict?'Conflict detected':'No conflict'} · score {loop?.multiTimeframe?.score??'—'}</span></article></div><div className="levels"><span>Entry <b>{money(loop?.signal?.entry)}</b></span><span>SL <b>{money(loop?.signal?.stopLoss)}</b></span><span>TP <b>{money(loop?.signal?.takeProfit)}</b></span><span>RR <b>{loop?.signal?.rr??'—'}</b></span></div></section>
  <section className="grid"><div className="section"><div className="sectionHead"><h2>{t.thesis}</h2><small>{loop?.chartPatterns?.primary||'No pattern'}</small></div><div className="body"><div className="chips"><span>{loop?.newsImpact?.level||'NO NEWS'}</span><span>{loop?.eventReaction?.level||'NO EVENT'}</span><span>{loop?.chartPatterns?.breakout||'NO BREAKOUT'}</span></div>{[...(loop?.risk?.reasons??[]),...(loop?.eventReaction?.reasons??[]),...(loop?.warnings??[])].slice(0,10).map((x,i)=><p className="bullet" key={`${x}-${i}`}>{x}</p>)}{!loop?.warnings?.length&&!loop?.risk?.reasons?.length&&<p className="muted">Validated inputs are currently within normal operating conditions.</p>}</div></div>
  <aside className="section"><div className="sectionHead"><h2>{t.learning}</h2><small>{metrics?.total?`${metrics.total} evaluated`:'—'}</small></div><div className="learning"><div><strong>{metrics?.winRate==null?'—':pct(metrics.winRate*100)}</strong><span>win rate</span></div><div><strong>{metrics?.averageReturnPct==null?'—':pct(metrics.averageReturnPct)}</strong><span>avg return</span></div><div><strong>{metrics?.averageCalibrationGap==null?'—':pct(metrics.averageCalibrationGap)}</strong><span>calibration gap</span></div></div><p className="muted">{metrics?.total?`${metrics.wins} wins · ${metrics.losses} losses`:t.history}</p></aside></section>
  <section className="section" id="news"><div className="sectionHead"><h2>{t.newsPulse}</h2><small>{loop?.newsImpact?.breakingCount??0} breaking · {loop?.newsImpact?.highImpactCount??0} high impact</small></div>{stories.slice(0,8).map((n,i)=><a className="news" href={n.url} target="_blank" rel="noreferrer" key={`${n.title}-${i}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><div><div className="tag">{n.category||'MARKET'} · {n.source}</div><h3>{n.title}</h3><p>{age(n.publishedAt)} ago</p></div><span className="arrow">↗</span></a>)}{!stories.length&&<div className="empty">No validated stories available.</div>}</section>
  <section className="watch section" id="watchlist"><div className="sectionHead"><h2>{t.watch}</h2><small>NO AUTO-TRADING</small></div><div className="watchGrid">{markets.slice(0,6).map(x=><button key={x.symbol} onClick={()=>setSymbol(x.symbol)}><b>{x.symbol.replace('USDT','')}</b><span>{money(x.price)}</span><em className={x.change24h>=0?'up':'down'}>{x.change24h>=0?'+':''}{x.change24h.toFixed(2)}%</em></button>)}</div></section>
  <footer className="footer"><b>MARKET/INTEL</b> · informational intelligence only · no automatic orders, transfers or withdrawals.</footer>
 </main>
}
