'use client';
import React,{useCallback,useEffect,useState} from 'react';
import AIChat from '@/app/components/AIChat';
type Market={symbol:string;name:string;price:number;change24h:number;source?:string;quality?:string};
type Loop={symbol:string;interval:string;generatedAt:string;dataValid:boolean;cycleId?:string;signal?:any;forecast?:any;consensus?:any;risk?:any;multiTimeframe?:any;chartPatterns?:any;newsImpact?:any;eventReaction?:any;warnings?:string[];news?:any[]};
type Metrics={total:number;wins:number;losses:number;winRate:number|null;averageReturnPct:number|null;averageCalibrationGap:number|null};
const h=React.createElement;
const money=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number(v)>100?0:2}).format(Number(v));
const pct=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':`${Number(v).toFixed(1)}%`;
const tone=(v:string)=>v==='LONG'||v==='BULLISH'?'up':v==='SHORT'||v==='BEARISH'?'down':'';
const ago=(v:string)=>{if(!v)return'—';const m=Math.max(0,Math.floor((Date.now()-Date.parse(v))/60000));return m<1?'now':m<60?`${m}m`:`${Math.floor(m/60)}h`};

export default function Home(){
 const [markets,setMarkets]=useState<Market[]>([]);const [loop,setLoop]=useState<Loop|null>(null);const [metrics,setMetrics]=useState<Metrics|null>(null);const [symbol,setSymbol]=useState('BTCUSDT');const [interval,setIntervalValue]=useState('15m');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [fa,setFa]=useState(false);const [installEvent,setInstallEvent]=useState<any>(null);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const rs=await Promise.all([fetch('/api/market',{cache:'no-store'}),fetch(`/api/loop?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}`,{cache:'no-store'}),fetch(`/api/forecast-metrics?symbol=${encodeURIComponent(symbol)}`,{cache:'no-store'})]);const md=await rs[0].json();const ld=await rs[1].json();const fd=await rs[2].json();if(!rs[1].ok)throw new Error(ld.error||'Live intelligence unavailable');setMarkets(md.markets||[]);setLoop(ld);setMetrics(fd.metrics||null)}catch(e){setError(e instanceof Error?e.message:'Live intelligence unavailable')}finally{setLoading(false)}},[symbol,interval]);
 useEffect(()=>{refresh();const id=setInterval(refresh,30000);return()=>clearInterval(id)},[refresh]);
 useEffect(()=>{const f=(e:Event)=>{e.preventDefault();setInstallEvent(e)};window.addEventListener('beforeinstallprompt',f);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>window.removeEventListener('beforeinstallprompt',f)},[]);
 const install=async()=>{if(!installEvent)return;installEvent.prompt();await installEvent.userChoice;setInstallEvent(null)};
 const s=loop?.signal||{},f=loop?.forecast||{},r=loop?.risk||{},c=loop?.consensus||{},m=loop?.multiTimeframe||{};const warnings=[...(r.reasons||[]),...(loop?.eventReaction?.reasons||[]),...(loop?.warnings||[])].slice(0,10);const text=(en:string,faText:string)=>fa?faText:en;
 const cards=markets.slice(0,6).map(x=>h('button',{className:`card ${x.symbol===symbol?'selected':''}`,key:x.symbol,onClick:()=>setSymbol(x.symbol)},h('div',{className:'label'},x.symbol.replace('USDT','')+'/USD'),h('div',{className:'price'},money(x.price)),h('div',{className:x.change24h>=0?'up':'down'},(x.change24h>=0?'+':'')+x.change24h.toFixed(2)+'%'),h('div',{className:'mini'},(x.quality||'live')+' · '+(x.source||'provider'))));
 const header=h('header',{className:'top'},h('a',{className:'brand',href:'#top'},'MARKET',h('span',null,'/'),'INTEL'),h('nav',{className:'nav'},h('a',{href:'#markets'},text('Markets','بازارها')),h('a',{href:'#intelligence'},text('Intelligence','هوش بازار')),h('a',{href:'#news'},text('News','اخبار')),h('a',{href:'#watchlist'},text('Watchlist','دیده‌بان'))),h('div',{className:'controls'},h('button',{className:'refresh',onClick:()=>setFa(!fa)},fa?'EN':'FA'),h('select',{value:symbol,onChange:e=>setSymbol((e.currentTarget as HTMLSelectElement).value)},['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','ADAUSDT'].map(x=>h('option',{key:x,value:x},x))),h('select',{value:interval,onChange:e=>setIntervalValue((e.currentTarget as HTMLSelectElement).value)},['5m','15m','1h','4h','1d'].map(x=>h('option',{key:x,value:x},x))),installEvent?h('button',{className:'install',onClick:install},text('Install','نصب اپ')):null,h('button',{className:'refresh',onClick:refresh},loading?'…':text('Refresh','بروزرسانی'))));
 const hero=h('section',{className:'hero',id:'top'},h('div',null,h('div',{className:'eyebrow'},h('i',{className:'dot'}),(loop?.dataValid?'LIVE':'LIMITED')+' · '+symbol+' · '+interval),h('h1',null,text('LIVE MARKET INTELLIGENCE','هوش زنده بازار'),h('br'),h('em',null,text('data → structure → consensus → validation','داده → ساختار → اجماع → اعتبارسنجی'))),h('p',null,text('Live market data, technical structure, multi-timeframe analysis, analyst consensus, news, risk and forecast evaluation in one cycle. No fabricated values.','داده بازار، ساختار تکنیکال، چندبازه‌ای، تحلیلگران، اخبار، ریسک و ارزیابی پیش‌بینی در یک چرخه زنده. بدون داده ساختگی.'))),h('div',{className:'status'},h('b',null,loop?.dataValid?'DATA VALID':'LIMITED DATA'),h('span',null,loop?.cycleId||'Waiting for cycle…'),h('small',null,loop?.generatedAt?ago(loop.generatedAt)+' ago':'—'),error?h('small',{className:'down'},error):null));
 const stat=(label:string,value:any,detail:any,cl?:string)=>h('article',{key:label},h('small',null,label),h('strong',{className:cl||''},value),h('span',null,detail));
 const command=h('section',{className:'command',id:'intelligence'},h('div',{className:'commandTop'},h('div',null,h('div',{className:'label'},text('SIGNAL','سیگنال')),h('div',{className:'big'},h('strong',{className:tone(s.direction)},s.direction||'NO TRADE'),h('b',null,pct(s.confidence))),h('div',{className:'meter'},h('i',{style:{width:`${Math.min(100,Math.max(0,Number(s.confidence)||0))}%`}}))),h('button',{className:'deep',onClick:refresh},text('DEEP SCAN','اسکن عمیق'))),h('div',{className:'statGrid'},stat('FORECAST',f.bias||'UNAVAILABLE',pct(f.confidence)+' · '+money(f.expectedLow)+' — '+money(f.expectedHigh),tone(f.bias)),stat('CONSENSUS',c.direction||'NO DATA',pct(c.confidence)+' · '+(c.views||0)+' analyst views'),stat('RISK',r.level||'UNKNOWN',(r.positionRisk||'—')+' · score '+(r.score??'—')),stat('MULTI-TIMEFRAME',String(m.alignment||'INSUFFICIENT').replaceAll('_',' '),(m.conflict?'Conflict detected':'No conflict')+' · score '+(m.score??'—'))),h('div',{className:'levels'},h('span',null,'Entry ',h('b',null,money(s.entry))),h('span',null,'SL ',h('b',null,money(s.stopLoss))),h('span',null,'TP ',h('b',null,money(s.takeProfit))),h('span',null,'RR ',h('b',null,s.rr??'—'))));
 const warningBody=h('div',{className:'body'},h('div',{className:'chips'},h('span',null,loop?.newsImpact?.level||'NO NEWS'),h('span',null,loop?.eventReaction?.level||'NO EVENT'),h('span',null,loop?.chartPatterns?.breakout||'NO BREAKOUT')),warnings.length?warnings.map((x:string,i:number)=>h('p',{className:'bullet',key:i},x)):h('p',{className:'muted'},'No active critical warnings from the current validation cycle.'));
 const track=h('aside',{className:'section'},h('div',{className:'sectionHead'},h('h2',null,text('FORECAST TRACK RECORD','سابقه یادگیری')),h('small',null,(metrics?.total||0)+' evaluated')),h('div',{className:'learning'},h('div',null,h('strong',null,metrics?.winRate==null?'—':pct(metrics.winRate*100)),h('span',null,'win rate')),h('div',null,h('strong',null,metrics?.averageReturnPct==null?'—':pct(metrics.averageReturnPct)),h('span',null,'avg return')),h('div',null,h('strong',null,metrics?.averageCalibrationGap==null?'—':pct(metrics.averageCalibrationGap)),h('span',null,'calibration gap'))),h('p',{className:'muted'},metrics?.total?`${metrics.wins} wins · ${metrics.losses} losses`:text('No evaluated history yet','هنوز سابقه ارزیابی کافی نیست')));
 const grid=h('section',{className:'grid'},h('div',{className:'section'},h('div',{className:'sectionHead'},h('h2',null,text('RISK · STRUCTURE · WARNINGS','ریسک، ساختار و هشدارها')),h('small',null,loop?.chartPatterns?.primary||'NO PATTERN')),warningBody),track);
 const news=(loop?.news||[]).slice(0,8).map((n:any,i:number)=>h('a',{className:'news',href:n.url,target:'_blank',rel:'noreferrer',key:i},h('span',{className:'rank'},String(i+1).padStart(2,'0')),h('div',null,h('div',{className:'tag'},(n.category||'MARKET')+' · '+n.source),h('h3',null,n.title),h('p',null,ago(n.publishedAt)+' ago')),h('span',{className:'arrow'},'↗')));
 const newsSection=h('section',{className:'section',id:'news'},h('div',{className:'sectionHead'},h('h2',null,text('NEWS PULSE','نبض اخبار')),h('small',null,(loop?.newsImpact?.sourceCount||0)+' sources · '+(loop?.newsImpact?.breakingCount||0)+' breaking · '+(loop?.newsImpact?.highImpactCount||0)+' high impact')),news.length?news:h('div',{className:'empty'},'No validated stories available.'));
 const watch=h('section',{className:'section watch',id:'watchlist'},h('div',{className:'sectionHead'},h('h2',null,text('WATCHLIST','دیده‌بان')),h('small',null,'NO AUTO-TRADING')),h('div',{className:'watchGrid'},markets.slice(0,6).map(x=>h('button',{key:x.symbol,onClick:()=>setSymbol(x.symbol)},h('b',null,x.symbol.replace('USDT','')),h('span',null,money(x.price)),h('em',{className:x.change24h>=0?'up':'down'},(x.change24h>=0?'+':'')+x.change24h.toFixed(2)+'%')))));
 const footer=h('footer',{className:'footer'},h('b',null,'MARKET/INTEL'),' · informational intelligence only · no automatic orders, transfers or withdrawals.');
 const chatContext={signal:s,forecast:f,risk:r,consensus:c,multiTimeframe:m,newsImpact:loop?.newsImpact,events:loop?.eventReaction,news:(loop?.news||[]).slice(0,10),warnings};
 return h(React.Fragment,null,h('main',{className:'shell',dir:fa?'rtl':'ltr'},header,hero,h('section',{className:'ticker',id:'markets'},cards),command,grid,newsSection,watch,footer),h(AIChat,{symbol,interval,context:chatContext,fa}));
}
