import type { AnalystOpinion } from './analyst-brain';

export type MemoryKind = 'OBSERVATION' | 'PREDICTION' | 'OUTCOME' | 'LESSON' | 'CONFLICT' | 'FACT';
export type AnalystOutcome = 'WIN' | 'LOSS' | 'INVALIDATED' | 'OPEN';
export type AnalystMemoryRecord = { id:string; analystId:string; kind:MemoryKind; timestamp:string; symbol:string; regime:string; summary:string; evidence:string[]; tags:string[]; confidence:number; outcome?:AnalystOutcome; returnPct?:number };
export type AnalystProfile = { analystId:string; observations:number; evaluatedPredictions:number; wins:number; losses:number; invalidated:number; open:number; winRate:number|null; averageReturnPct:number|null; confidenceReliability:number; currentWeight:number; specialization:string[]; recentLessons:string[]; lastUpdated:string|null };

const MAX_RECORDS=20000, MAX_LESSONS_PER_ANALYST=80;
const records:AnalystMemoryRecord[]=[]; const weights=new Map<string,number>();
let hydrated=false; let hydrationPromise:Promise<void>|null=null;
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
function ensureWeight(id:string){if(!weights.has(id))weights.set(id,1);return weights.get(id)??1;}
function hashId(v:string){let h=2166136261;for(let i=0;i<v.length;i++)h=Math.imul(h^v.charCodeAt(i),16777619);return `${Date.now().toString(36)}-${(h>>>0).toString(36)}`;}

async function persist(item:AnalystMemoryRecord){try{const m=await import('./persistent-memory');await m.persistMemory(item);}catch{/* DB is optional; runtime memory remains available. */}}

export async function initializePersistentMemory(){
  if(hydrated)return;
  if(hydrationPromise)return hydrationPromise;
  hydrationPromise=(async()=>{try{const m=await import('./persistent-memory');const [loaded,profiles]=await Promise.all([m.hydrateAnalystMemory(MAX_RECORDS),m.hydrateAnalystProfiles()]);if(loaded.length)records.splice(0,records.length,...loaded.slice(-MAX_RECORDS));for(const r of records)ensureWeight(r.analystId);for(const profile of profiles){if(Number.isFinite(profile.currentWeight))weights.set(profile.analystId,clamp(profile.currentWeight,.55,1.45));}}catch{/* no database configured or temporarily unavailable */}finally{hydrated=true;}})();
  return hydrationPromise;
}

export function remember(record:Omit<AnalystMemoryRecord,'id'|'timestamp'>){const item={...record,id:hashId(`${record.analystId}:${record.kind}:${record.summary}`),timestamp:new Date().toISOString()};records.push(item);if(records.length>MAX_RECORDS)records.splice(0,records.length-MAX_RECORDS);void persist(item);return item;}
export function rememberAnalystOpinions(symbol:string,regime:string,opinions:AnalystOpinion[]){for(const o of opinions)remember({analystId:o.id,kind:'PREDICTION',symbol,regime,summary:`${o.direction} ${o.score} / ${o.confidence}%`,evidence:o.evidence.slice(0,12),tags:[o.direction,regime,o.independentMethod],confidence:o.confidence});}
export function recordAnalystOutcome(analystId:string,symbol:string,regime:string,outcome:AnalystOutcome,returnPct:number,lesson:string){remember({analystId,kind:outcome==='OPEN'?'OBSERVATION':'OUTCOME',symbol,regime,summary:`${outcome}: ${returnPct.toFixed(4)}%`,evidence:lesson?[lesson]:[],tags:[outcome,regime],confidence:100,outcome,returnPct});if(lesson.trim())remember({analystId,kind:'LESSON',symbol,regime,summary:lesson.trim(),evidence:[],tags:[regime],confidence:100});adaptWeight(analystId);void persistProfile(analystId);}
function adaptWeight(id:string){const e=records.filter(r=>r.analystId===id&&r.kind==='OUTCOME'&&r.outcome!=='OPEN').slice(-120);if(e.length<20)return;const w=e.filter(r=>r.outcome==='WIN').length;const avg=e.reduce((s,r)=>s+(r.returnPct??0),0)/e.length;const sw=(w+10)/(e.length+20);const performance=clamp((sw-.5)*2+clamp(avg/5,-1,1),-1,1);const reliability=clamp(e.length/50,.35,1);const p=performance*(0.4+0.6*reliability);const previous=ensureWeight(id);const target=clamp(1+p*.45,.55,1.45);weights.set(id,Number(clamp(previous*.7+target*.3,.55,1.45).toFixed(4)));}
export function getAnalystMemory(id:string,limit=24){return records.filter(r=>r.analystId===id).slice(-Math.max(1,Math.min(200,limit)));}
export function retrieveRelevantMemories(id:string,query:string,symbol?:string,regime?:string,limit=12){const tokens=String(query).toLowerCase().split(/[^a-z0-9_-]+/).filter(Boolean);const now=Date.now();return records.filter(r=>r.analystId===id).map(r=>{const hay=`${r.symbol} ${r.regime} ${r.summary} ${r.evidence.join(' ')} ${r.tags.join(' ')}`.toLowerCase();const hits=tokens.reduce((n,t)=>n+(hay.includes(t)?1:0),0);const age=Math.max(0,(now-Date.parse(r.timestamp))/86400000);const recency=Math.exp(-age/30);const context=(symbol&&r.symbol===symbol.toUpperCase()?0.8:0)+(regime&&r.regime===regime?0.8:0);return {...r,relevance:Number((hits*2+context+recency+r.confidence/1000).toFixed(4))};}).sort((a,b)=>b.relevance-a.relevance).slice(0,Math.max(1,Math.min(50,limit)));}

export function getAdaptiveAnalystWeight(id:string,regime?:string){const global=ensureWeight(id);if(!regime)return global;const e=records.filter(r=>r.analystId===id&&r.kind==='OUTCOME'&&r.outcome!=='OPEN'&&r.regime===regime).slice(-80);if(e.length<12)return global;const wins=e.filter(r=>r.outcome==='WIN').length;const avg=e.reduce((s,r)=>s+(r.returnPct??0),0)/e.length;const wr=(wins+6)/(e.length+12);const signal=clamp((wr-.5)*1.6+clamp(avg/8,-.6,.6),-.8,.8);const contextualReliability=clamp(e.length/30,.35,1);const regimeWeight=clamp(1+signal*.3*(0.4+0.6*contextualReliability),.7,1.3);return Number(clamp(global*.65+regimeWeight*.35,.55,1.45).toFixed(4));}

export function getAnalystProfile(id:string):AnalystProfile{const mine=records.filter(r=>r.analystId===id);const outs=mine.filter(r=>r.kind==='OUTCOME'&&r.outcome);const ev=outs.filter(r=>r.outcome!=='OPEN');const wins=ev.filter(r=>r.outcome==='WIN').length;const losses=ev.filter(r=>r.outcome==='LOSS').length;const invalidated=ev.filter(r=>r.outcome==='INVALIDATED').length;const open=outs.filter(r=>r.outcome==='OPEN').length;const returns=ev.map(r=>r.returnPct??0);const winRate=ev.length?wins/ev.length:null;const averageReturnPct=returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:null;const predictions=mine.filter(r=>r.kind==='PREDICTION');const confidenceReliability=ev.length?clamp(0.35+Math.min(0.65,ev.length/50),.35,1):.35;const tags=new Map<string,number>();for(const r of mine.slice(-500))for(const tag of r.tags)tags.set(tag,(tags.get(tag)??0)+1);const specialization=[...tags.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([tag])=>tag);const lessons=mine.filter(r=>r.kind==='LESSON').slice(-MAX_LESSONS_PER_ANALYST);return{analystId:id,observations:mine.length,evaluatedPredictions:ev.length,wins,losses,invalidated,open,winRate,averageReturnPct,confidenceReliability,currentWeight:ensureWeight(id),specialization,recentLessons:lessons.slice(-8).map(r=>r.summary),lastUpdated:mine.at(-1)?.timestamp??null};}
async function persistProfile(id:string){try{const m=await import('./persistent-memory');await m.persistProfile(getAnalystProfile(id));}catch{/* optional persistence */}}
export function getAllAnalystProfiles(ids:string[]){return ids.map(getAnalystProfile);}
export function buildMemoryContext(id:string,query='',symbol?:string,regime?:string){return{profile:getAnalystProfile(id),memories:query?retrieveRelevantMemories(id,query,symbol,regime,12):getAnalystMemory(id,12),effectiveWeight:getAdaptiveAnalystWeight(id,regime)};}
