import { getAdvancedMarketData, type Candle } from './market-advanced';

export type TimeframeView={interval:string;trend:'BULLISH'|'BEARISH'|'NEUTRAL'|'UNKNOWN';momentum:'BULLISH'|'BEARISH'|'NEUTRAL'|'UNKNOWN';changePct:number|null;sampleSize:number;confidence:number};
export type MultiTimeframeSnapshot={baseInterval:string;views:TimeframeView[];alignment:'ALIGNED_BULLISH'|'ALIGNED_BEARISH'|'MIXED'|'INSUFFICIENT';score:number;conflict:boolean;warnings:string[]};

const ORDER=['1m','3m','5m','15m','30m','1h','2h','4h','6h','8h','12h','1d','3d','1w'];
const finite=(v:number|null|undefined):v is number=>v!==null&&v!==undefined&&Number.isFinite(v);
function view(interval:string,c:Candle[]):TimeframeView{const valid=c.filter(x=>finite(x.close)&&x.close>0).sort((a,b)=>a.openTime-b.openTime);if(valid.length<5)return{interval,trend:'UNKNOWN',momentum:'UNKNOWN',changePct:null,sampleSize:valid.length,confidence:0};const closes=valid.slice(-20).map(x=>x.close);const first=closes[0],last=closes[closes.length-1],changePct=(last-first)/first*100;const fast=closes.slice(-5).reduce((a,b)=>a+b,0)/Math.min(5,closes.length);const slow=closes.reduce((a,b)=>a+b,0)/closes.length;const trend=fast>slow*1.001?'BULLISH':fast<slow*.999?'BEARISH':'NEUTRAL';const momentum=changePct>.3?'BULLISH':changePct<-.3?'BEARISH':'NEUTRAL';const confidence=Math.min(100,Math.round(40+Math.min(40,valid.length*2)+((trend===momentum&&trend!=='NEUTRAL')?20:0)));return{interval,trend,momentum,changePct,sampleSize:valid.length,confidence};}
export async function analyzeMultiTimeframe(symbol:string,baseInterval='15m'):Promise<MultiTimeframeSnapshot>{const idx=Math.max(0,ORDER.indexOf(baseInterval));const intervals=ORDER.slice(Math.max(0,idx-2),Math.min(ORDER.length,idx+3));const results=await Promise.all(intervals.map(async interval=>({interval,data:await getAdvancedMarketData(symbol,interval,100)})));const views=results.map(x=>view(x.interval,x.data.futures.candles.length>=5?x.data.futures.candles:x.data.spot.candles));const usable=views.filter(x=>x.trend!=='UNKNOWN');const bulls=usable.filter(x=>x.trend==='BULLISH').length,bears=usable.filter(x=>x.trend==='BEARISH').length;const alignment=usable.length<3?'INSUFFICIENT':bulls>=Math.ceil(usable.length*.7)?'ALIGNED_BULLISH':bears>=Math.ceil(usable.length*.7)?'ALIGNED_BEARISH':'MIXED';const conflict=bulls>0&&bears>0;const score=usable.length?Math.round((Math.max(bulls,bears)/usable.length)*100):0;const warnings:string[]=[];if(alignment==='MIXED')warnings.push('Multi-timeframe structure is mixed; reduce directional confidence.');if(alignment==='INSUFFICIENT')warnings.push('Not enough validated timeframe data for alignment.');return{baseInterval,views,alignment,score,conflict,warnings};}
