'use client';
import React,{useEffect,useState} from 'react';
type Ex={id:string,name:string,environment:string,account_type:string,permissions:any,connected:boolean,last_sync:string};
type Risk={execution_mode:string;autonomous_enabled:boolean;emergency_stop:boolean;max_order_usd:number;max_position_usd:number;max_daily_loss_usd:number;max_trades:number};
export default function SettingsPage(){
 const [xs,setXs]=useState<Ex[]>([]),[risk,setRisk]=useState<Risk|null>(null),[apiKey,setApiKey]=useState(''),[secret,setSecret]=useState(''),[env,setEnv]=useState('LIVE'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[detail,setDetail]=useState<any>(null);
 async function load(){const [a,b]=await Promise.all([fetch('/api/exchanges',{cache:'no-store'}),fetch('/api/trading/risk',{cache:'no-store'})]);const x=await a.json(),r=await b.json();if(x.ok)setXs(x.exchanges||[]);if(r.ok)setRisk(r.risk);if(!x.ok)setMsg(x.error||'Exchange storage unavailable')}
 useEffect(()=>{load()},[]);
 async function connect(){setBusy(true);setMsg('');try{const r=await fetch('/api/exchanges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({exchange:'binance',apiKey,apiSecret:secret,environment:env,accountType:'SPOT'})});const j=await r.json();if(j.ok){setMsg('CONNECTED — Binance API verified.');setApiKey('');setSecret('');await load()}else setMsg(j.error||'CONNECTION FAILED')}catch{setMsg('CONNECTION FAILED')}finally{setBusy(false)}}
 async function saveRisk(){if(!risk)return;setBusy(true);setMsg('');try{const r=await fetch('/api/trading/risk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(risk)});const j=await r.json();setMsg(j.ok?'RISK SETTINGS SAVED':j.error||'SAVE FAILED');if(j.ok)setRisk(j.risk)}catch{setMsg('SAVE FAILED')}finally{setBusy(false)}}
 async function stop(){if(!risk)return;const next=!risk.emergency_stop;setRisk({...risk,emergency_stop:next});try{const r=await fetch('/api/trading/emergency-stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:next})});const j=await r.json();setMsg(j.ok?(next?'EMERGENCY STOP ON':'EMERGENCY STOP OFF'):j.error||'FAILED')}catch{setMsg('FAILED')}}
 async function view(id:string,op:string){const r=await fetch('/api/exchanges/'+id+'?op='+op+'&symbol=BTCUSDT');setDetail(await r.json())}
 return <main style={{minHeight:'100vh',background:'#06080c',color:'#e8edf2',padding:'24px 18px',fontFamily:'system-ui,sans-serif'}}><div style={{maxWidth:1050,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><a href="/" style={{color:'#8ff5ae',textDecoration:'none'}}>← FLI</a><h1 style={{fontSize:34,margin:'8px 0 4px'}}>Settings</h1><p style={{color:'#9aa59f',margin:0}}>تمام کنترل‌های اتصال، امنیت و اجرای معامله در یک محل.</p></div><a href="/" style={small}>Dashboard</a></div>
 <section style={card}><h2>Exchange Manager</h2><p style={muted}>کلیدها فقط به Backend ارسال می‌شوند و Secret در رابط یا DRO نمایش داده نمی‌شود.</p><label>API Key<input value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off" style={input}/></label><label>API Secret<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="new-password" style={input}/></label><label>Environment<select value={env} onChange={e=>setEnv(e.target.value)} style={input}><option>LIVE</option><option>TESTNET</option></select></label><button disabled={busy} onClick={connect} style={button}>{busy?'TESTING…':'TEST CONNECTION + CONNECT'}</button></section>
 <section style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><h2>Trading & Risk</h2><p style={muted}>Execution mode، محدودیت‌ها و توقف اضطراری.</p></div>{risk&&<button onClick={stop} style={{...button,background:risk.emergency_stop?'#ff6675':'#8ff5ae'}}>{risk.emergency_stop?'EMERGENCY STOP: ON':'EMERGENCY STOP: OFF'}</button>}</div>{risk&&<><div style={grid}><label>Execution Mode<select value={risk.execution_mode} onChange={e=>setRisk({...risk,execution_mode:e.target.value})} style={input}><option>PAPER</option><option>CONFIRM</option><option>AUTONOMOUS</option></select></label><label>Max Order USD<input type="number" value={risk.max_order_usd} onChange={e=>setRisk({...risk,max_order_usd:Number(e.target.value)})} style={input}/></label><label>Max Position USD<input type="number" value={risk.max_position_usd} onChange={e=>setRisk({...risk,max_position_usd:Number(e.target.value)})} style={input}/></label><label>Max Daily Loss USD<input type="number" value={risk.max_daily_loss_usd} onChange={e=>setRisk({...risk,max_daily_loss_usd:Number(e.target.value)})} style={input}/></label><label>Max Daily Trades<input type="number" value={risk.max_trades} onChange={e=>setRisk({...risk,max_trades:Number(e.target.value)})} style={input}/></label><label style={{display:'flex',alignItems:'center',gap:8,marginTop:8}}><input type="checkbox" checked={risk.autonomous_enabled} onChange={e=>setRisk({...risk,autonomous_enabled:e.target.checked})}/> Enable Autonomous Engine</label></div><button onClick={saveRisk} disabled={busy} style={button}>SAVE RISK SETTINGS</button></>}</section>
 <section style={card}><h2>Connected Exchanges</h2>{xs.length===0?<div style={muted}>No exchange connected.</div>:xs.map(x=><div key={x.id} style={item}><div><b>{x.name.toUpperCase()}</b><div style={{color:'#8ff5ae',marginTop:5}}>● {x.connected?'CONNECTED':'DISCONNECTED'}</div><small>{x.environment} · {x.account_type}</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>view(x.id,'account')} style={small}>Account</button><button onClick={()=>view(x.id,'balance')} style={small}>Balance</button><button onClick={()=>view(x.id,'orders')} style={small}>Orders</button><button onClick={()=>view(x.id,'positions')} style={small}>Positions</button></div></div>)}</section>
 {msg&&<div style={{...card,color:msg.includes('FAILED')||msg.includes('failed')?'#ff8e8e':'#8ff5ae'}}>{msg}</div>}{detail&&<section style={{...card,whiteSpace:'pre-wrap',overflow:'auto'}}><button onClick={()=>setDetail(null)} style={small}>Close</button><pre>{JSON.stringify(detail,null,2)}</pre></section>}
 </div></main>}
const input:any={display:'block',width:'100%',boxSizing:'border-box',margin:'7px 0 16px',padding:12,borderRadius:10,border:'1px solid #2a3932',background:'#070b0a',color:'#fff'};
const button:any={padding:'12px 16px',border:0,borderRadius:10,background:'#8ff5ae',color:'#061008',fontWeight:900,cursor:'pointer'};
const small:any={padding:'8px 11px',borderRadius:9,border:'1px solid #33443b',background:'#101713',color:'#dce7e0',textDecoration:'none'};
const card:any={marginTop:18,padding:20,border:'1px solid #26332d',borderRadius:16,background:'#0b1110'};
const item:any={marginTop:10,padding:14,border:'1px solid #202c26',borderRadius:12,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'};
const muted:any={color:'#87948d',fontSize:12,lineHeight:1.6};
const grid:any={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12};
